spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${S3_BUCKET}